# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kyungryul Back
title: AI engineer
email: rudfuf0822@korea.ac.kr
website: https://github.com/KR-0822

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  KR-0822
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: rudfuf_0822
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_kr.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello. I'm 경렬, an undergraduate Student at Korea University. 
  I have been fortunate to have some great opportunities to work on various projects and activities, collaborating with individuals from diverse backgrounds. 
  
  Currently, I am focusing on a NLP project of the course COSE461, Persona dialog generation[TBD] hoping to make a great chatbot with three of my teamates. 
  
  I am extremely passionate about exploring the cutting-edge fields of NLP and AI, I am eager to further my education and experience in these exciting areas.
  
  I am most skilled in: <mark>Python</mark> , <mark>Huggingface</mark> , <mark>Team projects</mark> , <mark>Sports and Games</mark>


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: These are some NLP, AI related projects I've done Since 2022.
        link: https://github.com/KR-0822
        # link_text: Project Website
        additional_links:
          - title: # KR/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/KR-0822
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        sub_title: 
        quote: 
        description: 
        
      - layout: top-middle
        title: #
        link: https://github.com/KR-0822/DataCampusKorea8
        # link_text: Project Website
        additional_links:
          - title: # KR/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/KR-0822/DataCampusKorea8
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        sub_title: Data Campus @Korea Univ. (데이터청년캠퍼스 고려대과정)
        quote: >
          This was the first group project I had worked on related to AI, aimed to imitating the Dall-E. \n
        
          As a result of working on this project, I developed a keen interests in [NLP] and [Generative models].
          
          We decided to create a text-to-image multimodal using a CLIP model. Since this was our first AI project, we studied intensively every day and tried to catch up the model.
        
        description: 
      
      - layout: top-middle
        title: #
        link: https://github.com/KR-0822/PolarBear
        # link_text: Project Website
        additional_links:
          - title: # KR/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/KR-0822/PolarBear
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        sub_title: AI Bootcamp, team [Polarbear] (Korea.Univ Winter school)
        quote: >
          In this project, I tried tuning the LSTM model. I tried changing both the hyperparameter and the hidden layer of the Conv-LSTM model. 
        
          The intersting thing was by rule of thumb, I learned that batch normalization didn't really work well in the LSTM model and found the Hinton's LayerNormalization and tried using 
        
        description: 
        
        
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Korea Univ, AI & Mobility (AIM) Lab
        link: sites.google.com/view/aimlab-kuee/home?authuser=0
        link_text: AI and Mobility (AIM) Lab, Korea Univ
        sub_title: Undergraduate Intern
        caption: SEP.2022 - Present
        quote: >
          Working as an Undergraduate Intern in AIM lab ~~~~~~~~~~~
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Korea University
        caption: 2022 - Present
        sub_title: Electrical Engineering, Interdisciplinary Major in Artificial Intelligence
        quote: >
        
        description: | # this will include new lines to allow paragraphs
          My Interdisciplinary Major is Artificial Intelligence. I took a course ARTIFICIAL INTELLIGENCE, Ethics of Artificial Intelligence, MACHINE LEARNING, NATURAL LANGUAGE PROCESSING, INFORMATION THEORY AND INFERENCE LEARNING. 
          
          Also I'm a committe member of four clubs, *HandS*(Electrical Engineering Club), *DevKor*(Software developing Club), *Quick*(Quantum studying club), *Deluxe*(Gaming club)

          
      - layout: left
        title: Dongguk University
        caption: 2018 - 2021
        sub_title: Industrial Systems Engineering
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
